from typing import Any

import pytest

from src.vacancies import Vacancy


@pytest.fixture
def hh_data() -> list:
    return [
        {
            "id": "111862583",
            "premium": False,
            "name": "Frontend-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "Янгихаётский район, Ташкент Индекс",
                "building": None,
                "lat": 41.200287,
                "lng": 69.237615,
                "description": None,
                "raw": "Ташкент, Янгихаётский район, Ташкент Индекс",
                "metro": None,
                "metro_stations": [],
                "id": "16194487",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-26T11:17:10+0300",
            "created_at": "2024-11-26T11:17:10+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=111862583",
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/111862583?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/111862583",
            "relations": [],
            "employer": {
                "id": "11281034",
                "name": "VODIY SOFT HUB",
                "url": "https://api.hh.ru/employers/11281034",
                "alternate_url": "https://hh.ru/employer/11281034",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11281034",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "React TypeScript yoki Next.js TypeScript bo‘yicha bilim.",
                "responsibility": "Dasturiy ta'minotimizning server qismiga ishlov berish va uni qo‘llab-quvvatlash.",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "99579827",
            "premium": False,
            "name": "Системный аналитик",
            "department": {"id": "6591-6591-it", "name": "ПАО «Промсвязьбанк», ИТ"},
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
            "salary": {"from": 2000000, "to": 10000000, "currency": "UZS", "gross": False},
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-05T12:12:48+0300",
            "created_at": "2024-11-05T12:12:48+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=99579827",
            "branding": {"type": "MAKEUP", "tariff": None},
            "show_logo_in_search": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/99579827?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/99579827",
            "relations": [],
            "employer": {
                "id": "6591",
                "name": "ПСБ (ПАО «Промсвязьбанк»)",
                "url": "https://api.hh.ru/employers/6591",
                "alternate_url": "https://hh.ru/employer/6591",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/681020.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3165213.png",
                    "90": "https://img.hhcdn.ru/employer-logo/3165212.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=6591",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Развитые коммуникационные навыки, умение находить общий язык...",
                "responsibility": "Участие в разработке новых продуктов и платформ...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "148", "name": "Системный аналитик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "112182612",
            "premium": False,
            "name": "Frontend-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Tashkent",
                "street": "Amir Temur Avenue",
                "building": "95A",
                "lat": 41.332733,
                "lng": 69.283797,
                "description": None,
                "raw": "Tashkent, Amir Temur Avenue, 95A",
                "metro": None,
                "metro_stations": [],
                "id": "15973112",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-29T18:04:12+0300",
            "created_at": "2024-11-29T18:04:12+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=112182612",
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/112182612?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/112182612",
            "relations": [],
            "employer": {
                "id": "11085843",
                "name": "DIONYSOS",
                "url": "https://api.hh.ru/employers/11085843",
                "alternate_url": "https://hh.ru/employer/11085843",
                "logo_urls": {
                    "240": "https://img.hhcdn.ru/employer-logo/7058119.jpeg",
                    "90": "https://img.hhcdn.ru/employer-logo/7058118.jpeg",
                    "original": "https://img.hhcdn.ru/employer-logo-original/1359552.jpg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11085843",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Сильные навыки работы с VueJS v2/v3 и соответствующий профессиональный опыт...",
                "responsibility": "WMS (Warehouse Management System): Этот инструмент помогает складам...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]


@pytest.fixture
def hh_data_2() -> list:
    return [
        {
            "id": "111862583",
            "premium": False,
            "name": "Frontend-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": {"from": 500000, "to": None, "currency": "USD", "gross": False},
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "Янгихаётский район, Ташкент Индекс",
                "building": None,
                "lat": 41.200287,
                "lng": 69.237615,
                "description": None,
                "raw": "Ташкент, Янгихаётский район, Ташкент Индекс",
                "metro": None,
                "metro_stations": [],
                "id": "16194487",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-26T11:17:10+0300",
            "created_at": "2024-11-26T11:17:10+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=111862583",
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/111862583?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/111862583",
            "relations": [],
            "employer": {
                "id": "11281034",
                "name": "VODIY SOFT HUB",
                "url": "https://api.hh.ru/employers/11281034",
                "alternate_url": "https://hh.ru/employer/11281034",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11281034",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "React TypeScript yoki Next.js TypeScript bo‘yicha bilim...",
                "responsibility": "Dasturiy ta'minotimizning server qismiga ishlov berish...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "99579827",
            "premium": False,
            "name": "Системный аналитик",
            "department": {"id": "6591-6591-it", "name": "ПАО «Промсвязьбанк», ИТ"},
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
            "salary": {"from": 130000, "to": 150000, "currency": "RUB", "gross": False},
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-05T12:12:48+0300",
            "created_at": "2024-11-05T12:12:48+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=99579827",
            "branding": {"type": "MAKEUP", "tariff": None},
            "show_logo_in_search": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/99579827?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/99579827",
            "relations": [],
            "employer": {
                "id": "6591",
                "name": "ПСБ (ПАО «Промсвязьбанк»)",
                "url": "https://api.hh.ru/employers/6591",
                "alternate_url": "https://hh.ru/employer/6591",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/681020.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3165213.png",
                    "90": "https://img.hhcdn.ru/employer-logo/3165212.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=6591",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Развитые коммуникационные навыки, умение находить общий язык...",
                "responsibility": "Участие в разработке новых продуктов и платформ. Сбор...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "148", "name": "Системный аналитик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "112182612",
            "premium": False,
            "name": "Frontend-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": {"from": None, "to": 100, "currency": "USD", "gross": False},
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Tashkent",
                "street": "Amir Temur Avenue",
                "building": "95A",
                "lat": 41.332733,
                "lng": 69.283797,
                "description": None,
                "raw": "Tashkent, Amir Temur Avenue, 95A",
                "metro": None,
                "metro_stations": [],
                "id": "15973112",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2024-11-29T18:04:12+0300",
            "created_at": "2024-11-29T18:04:12+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=112182612",
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/112182612?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/112182612",
            "relations": [],
            "employer": {
                "id": "11085843",
                "name": "DIONYSOS",
                "url": "https://api.hh.ru/employers/11085843",
                "alternate_url": "https://hh.ru/employer/11085843",
                "logo_urls": {
                    "240": "https://img.hhcdn.ru/employer-logo/7058119.jpeg",
                    "90": "https://img.hhcdn.ru/employer-logo/7058118.jpeg",
                    "original": "https://img.hhcdn.ru/employer-logo-original/1359552.jpg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11085843",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Сильные навыки работы с VueJS v2/v3 и соответствующий профессиональный опыт...",
                "responsibility": "WMS (Warehouse Management System): Этот инструмент помогает складам...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]


@pytest.fixture
def hh_response() -> dict:
    return {
        "items": [
            {
                "id": "111862583",
                "premium": False,
                "name": "Frontend-разработчик",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
                "salary": None,
                "type": {"id": "open", "name": "Открытая"},
                "address": {
                    "city": "Ташкент",
                    "street": "Янгихаётский район, Ташкент Индекс",
                    "building": None,
                    "lat": 41.200287,
                    "lng": 69.237615,
                    "description": None,
                    "raw": "Ташкент, Янгихаётский район, Ташкент Индекс",
                    "metro": None,
                    "metro_stations": [],
                    "id": "16194487",
                },
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-11-26T11:17:10+0300",
                "created_at": "2024-11-26T11:17:10+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=111862583",
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/111862583?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/111862583",
                "relations": [],
                "employer": {
                    "id": "11281034",
                    "name": "VODIY SOFT HUB",
                    "url": "https://api.hh.ru/employers/11281034",
                    "alternate_url": "https://hh.ru/employer/11281034",
                    "logo_urls": None,
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11281034",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "React TypeScript yoki Next.js TypeScript bo‘yicha bilim...",
                    "responsibility": "Dasturiy ta'minotimizning server qismiga ishlov berish...",
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
                "accept_incomplete_resumes": False,
                "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "99579827",
                "premium": False,
                "name": "Системный аналитик",
                "department": {"id": "6591-6591-it", "name": "ПАО «Промсвязьбанк», ИТ"},
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
                "salary": {"from": 2000000, "to": 10000000, "currency": "UZS", "gross": False},
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-11-05T12:12:48+0300",
                "created_at": "2024-11-05T12:12:48+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=99579827",
                "branding": {"type": "MAKEUP", "tariff": None},
                "show_logo_in_search": True,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/99579827?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/99579827",
                "relations": [],
                "employer": {
                    "id": "6591",
                    "name": "ПСБ (ПАО «Промсвязьбанк»)",
                    "url": "https://api.hh.ru/employers/6591",
                    "alternate_url": "https://hh.ru/employer/6591",
                    "logo_urls": {
                        "original": "https://img.hhcdn.ru/employer-logo-original/681020.png",
                        "240": "https://img.hhcdn.ru/employer-logo/3165213.png",
                        "90": "https://img.hhcdn.ru/employer-logo/3165212.png",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=6591",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Развитые коммуникационные навыки, умение находить общий язык...",
                    "responsibility": "Участие в разработке новых продуктов и платформ...",
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "professional_roles": [{"id": "148", "name": "Системный аналитик"}],
                "accept_incomplete_resumes": False,
                "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "112182612",
                "premium": False,
                "name": "Frontend-разработчик",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
                "salary": None,
                "type": {"id": "open", "name": "Открытая"},
                "address": {
                    "city": "Tashkent",
                    "street": "Amir Temur Avenue",
                    "building": "95A",
                    "lat": 41.332733,
                    "lng": 69.283797,
                    "description": None,
                    "raw": "Tashkent, Amir Temur Avenue, 95A",
                    "metro": None,
                    "metro_stations": [],
                    "id": "15973112",
                },
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-11-29T18:04:12+0300",
                "created_at": "2024-11-29T18:04:12+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=112182612",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/112182612?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/112182612",
                "relations": [],
                "employer": {
                    "id": "11085843",
                    "name": "DIONYSOS",
                    "url": "https://api.hh.ru/employers/11085843",
                    "alternate_url": "https://hh.ru/employer/11085843",
                    "logo_urls": {
                        "240": "https://img.hhcdn.ru/employer-logo/7058119.jpeg",
                        "90": "https://img.hhcdn.ru/employer-logo/7058118.jpeg",
                        "original": "https://img.hhcdn.ru/employer-logo-original/1359552.jpg",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11085843",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Сильные навыки работы с VueJS v2/v3 и соответствующий профессиональный опыт...",
                    "responsibility": "WMS (Warehouse Management System): Этот инструмент помогает складам...",
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
                "accept_incomplete_resumes": False,
                "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
        ]
    }


@pytest.fixture
def vacancy_object() -> Any:
    return Vacancy(
        "123",
        "Python Developer",
        "<https://hh.ru/vacancy/123456>",
        "100000-150000 руб.",
        "Яндекс",
        "Требования: опыт работы от 3 лет...",
        "Частичная занятость",
        "Удаленная работа",
    )


@pytest.fixture
def vacancy_object_2() -> Any:
    return Vacancy(
        "124",
        "Системный аналитик",
        "<https://hh.ru/vacancy/123457>",
        "До 100000 руб.",
        "ООО Ромашка",
        "Требования: опыт работы от 3 лет...",
        "Полная занятость",
        "Удаленная работа",
    )


@pytest.fixture
def vacancies_list(vacancy_object: Any, vacancy_object_2: Any) -> list:
    return [vacancy_object, vacancy_object_2]


@pytest.fixture
def vacancy_dict() -> dict:
    return {
        "vacancy_id": "123",
        "name": "Python Developer",
        "link": "<https://hh.ru/vacancy/123456>",
        "salary_from": 100000,
        "salary_to": 150000,
        "salary_range": "100000-150000 руб.",
        "employer": "Яндекс",
        "requirement": "Требования: опыт работы от 3 лет...",
        "employment": "Частичная занятость",
        "schedule": "Удаленная работа",
    }


@pytest.fixture
def file_data() -> dict:
    return {
        "items": [
            {
                "vacancy_id": 125,
                "name": "Python Developer",
                "link": "<https://hh.ru/vacancy/123456>",
                "salary_from": "100000",
                "salary_to": "150000",
                "salary_range": "100000-150000 руб.",
                "employer": "Яндекс",
                "requirement": "Требования: опыт работы от 3 лет...",
                "employment": "Частичная занятость",
                "schedule": "Удаленная работа",
            },
            {
                "vacancy_id": 121,
                "name": "Python Developer",
                "link": "<https://hh.ru/vacancy/123456>",
                "salary_from": "100000",
                "salary_to": "150000",
                "salary_range": "100 000-150 000 руб.",
                "employer": "Яндекс",
                "requirement": "Требования: опыт работы от 3 лет...",
                "employment": "Частичная занятость",
                "schedule": "Удаленная работа",
            },
        ]
    }
